### 사이트 기본 설정 ###
title: Daeyeon Lee # 사이트 제목 (브라우저 탭, 헤더에 표시)
description: >- # 사이트 설명 (메인 페이지에 표시)
  Frontend Developer <br>                  
  끊임없이 배우고 성장하는 개발자입니다.
baseurl: "" # 사이트 기본 URL (루트 도메인 사용시 빈 문자열)
repository: daeyeon-lee/daeyeon-lee.github.io # GitHub 저장소 (프로젝트 자동 import용)
remote_theme: yousinix/portfolYOU # 사용할 Jekyll 테마
open_new_tab: true # 외부 링크를 새 탭에서 열기

### 플러그인 설정 ###
plugins:
  - jemoji # 이모지 플러그인 (마크다운에서 :smile: 같은 이모지 사용 가능)

### 네비게이션 바 설정 ###
nav_exclude: # 네비게이션 바에서 제외할 페이지들
  - pages/tags.html # 태그 페이지 제외
  - pages/404.html # 404 페이지 제외
  - pages/index.md # 인덱스 페이지 제외

### 작성자 정보 ###
author:
  name: 이대연 # 작성자 이름 (About 페이지, 푸터 등에 표시)
  image: /images/증명사진.
  jpg # 프로필 이미지 경로
  email: angellee98@naver.com # 이메일 주소 (mailto 링크 생성)
  github: daeyeon-lee # GitHub 사용자명 (https://github.com/daeyeon-lee)
  # linkedin        : daeyeon-lee                            # LinkedIn 프로필 (선택사항)
  # behance         : your_username                          # Behance (디자인 포트폴리오, 선택사항)
  # facebook        : your_username                          # Facebook (선택사항)
  # instagram       : your_username                          # Instagram (선택사항)
  # medium          : your_username                          # Medium 블로그 (선택사항)
  # stackoverflow   : your_user_id                           # Stack Overflow ID (선택사항)
  # twitter         : your_username                          # Twitter (선택사항)

### 블로그 포스트 설정 ###
permalink: /blog/:title # 블로그 포스트 URL 형식 (/blog/포스트제목)

### 컬렉션 설정 ###
collections:
  projects: # 프로젝트 컬렉션
    output: true # 각 프로젝트를 개별 페이지로 생성
    permalink: /projects/:name # 프로젝트 URL 형식 (/projects/프로젝트명)
  elements: # 문서용 요소 컬렉션
    output: true # 페이지 생성

### Disqus 댓글 시스템 ###
disqus:
  shortname: your-short-name-disqus # Disqus 사이트 shortname (댓글 기능 사용시 설정)

### Google Analytics 분석 ###
analytics:
  enabled: false # 분석 기능 활성화 (true로 변경하면 사용)
  google:
    tracking_id: your-google-tracking-id # Google Analytics 추적 ID

### Buy me a coffee 후원 버튼 ###
buymeacoffee:
  enabled: false # 후원 버튼 활성화 (true로 변경하면 사용)
  username: your_username # Buy me a coffee 사용자명
  color: "#007bff" # 버튼 색상
  message: "Thank you for visiting." # 버튼 옆에 표시할 메시지
  description: "Support me on Buy me a coffee!" # 버튼 설명

### 컬렉션별 기본 설정 ###
defaults:
  - scope:
      path: "" # 모든 프로젝트 파일에 적용
      type: "projects" # 프로젝트 타입
    values:
      layout: "page" # 기본 레이아웃: page
  - scope:
      path: "" # 모든 요소 파일에 적용
      type: "elements" # 요소 타입
    values:
      layout: "element" # 기본 레이아웃: element
  - scope:
      path: "" # 모든 포스트 파일에 적용
      type: "posts" # 포스트 타입
    values:
      comments: false # 댓글 기능 비활성화 (true로 변경하면 활성화)

### Jekyll 빌드 제외 파일 ###
exclude:
  - README.md # README 파일 제외
  - CONTRIBUTING.md # 기여 가이드 제외
  - LICENSE # 라이선스 파일 제외
  - "*.log" # 로그 파일 제외
